#Build the image for Devboard frontend
name: CI
on:
 push:
   branches: [main]
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v7
        
      - name: Docker setup
        uses: action/login-action@v4
        with:
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push 
        uses: docker/build-push-action@v7
        with:
          push:
          tags: ${{ vars.DOCKERHUB_USERNAME }}/docker-fe-master:latest
